### ISSUE TITLE
operator ==  conflict  with  std::vector::iterator

### ISSUE THREAD

**Issue by zxckiller** [calccrypto/uint256_t#10]
```
#include <vector>
#include "uint256_t/uint256_t.h"

int main()
{
	std::vector<uint256_t> v;
	std::vector<uint256_t>::iterator it;
	if (it == v.end())
	{
		//do something
	}

    return 0;
}
```
this code in vs2017 I got this error:
`error C2666: 'std::_Vector_const_iterator<std::_Vector_val<std::_Simple_types<_Ty>>>::operator ==': 4 overloads have similar conversions`

**Comment by calccrypto** [comment]
I might need a bit more of the error message. I do not see where there are 4 similar overloads, and cannot for the life of me figure out how to get Visual Studio to do anything.

Try adding `explicit`s in front of the constructors.

**Comment by zxckiller** [comment]
1>ConsoleApplication1.cpp
1>c:\users\zxc_work\documents\visual studio 2017\projects\consoleapplication1\consoleapplication1.cpp(13): error C2666: 'std::_Vector_const_iterator<std::_Vector_val<std::_Simple_types<_Ty>>>::operator ==': 4 overloads have similar conversions
1>        with
1>        [
1>            _Ty=uint256_t
1>        ]
1>c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.14.26428\include\vector(191): note: could be 'bool std::_Vector_const_iterator<std::_Vector_val<std::_Simple_types<_Ty>>>::operator ==(const std::_Vector_const_iterator<std::_Vector_val<std::_Simple_types<_Ty>>> &) const'
1>        with
1>        [
1>            _Ty=uint256_t
1>        ]
1>c:\users\zxc_work\documents\visual studio 2017\projects\consoleapplication1\uint256_t\uint256_t.h(431): note: or       'bool operator ==(const uint128_t &,const uint256_t &)'
1>c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.14.26428\include\exception(320): note: or       'bool std::operator ==(const std::exception_ptr &,const std::exception_ptr &) noexcept' [found using argument-dependent lookup]
1>c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.14.26428\include\exception(325): note: or       'bool std::operator ==(std::nullptr_t,const std::exception_ptr &) noexcept' [found using argument-dependent lookup]
1>c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.14.26428\include\exception(330): note: or       'bool std::operator ==(const std::exception_ptr &,std::nullptr_t) noexcept' [found using argument-dependent lookup]
1>c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.14.26428\include\system_error(266): note: or       'bool std::operator ==(const std::error_code &,const std::error_code &) noexcept' [found using argument-dependent lookup]
1>c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.14.26428\include\system_error(272): note: or       'bool std::operator ==(const std::error_code &,const std::error_condition &) noexcept' [found using argument-dependent lookup]
1>c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.14.26428\include\system_error(278): note: or       'bool std::operator ==(const std::error_condition &,const std::error_code &) noexcept' [found using argument-dependent lookup]
1>c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.14.26428\include\system_error(284): note: or       'bool std::operator ==(const std::error_condition &,const std::error_condition &) noexcept' [found using argument-dependent lookup]
1>c:\users\zxc_work\documents\visual studio 2017\projects\consoleapplication1\uint256_t\uint256_t.h(433): note: or       'bool operator ==<std::_Vector_iterator<std::_Vector_val<std::_Simple_types<_Ty>>>>(const T &,const uint256_t &)'
1>        with
1>        [
1>            _Ty=uint256_t,
1>            T=std::_Vector_iterator<std::_Vector_val<std::_Simple_types<uint256_t>>>
1>        ]
1>c:\users\zxc_work\documents\visual studio 2017\projects\consoleapplication1\uint256_t\uint128_t.h(376): note: or       'bool operator ==<std::_Vector_iterator<std::_Vector_val<std::_Simple_types<_Ty>>>>(const T &,const uint128_t &)'
1>        with
1>        [
1>            _Ty=uint256_t,
1>            T=std::_Vector_iterator<std::_Vector_val<std::_Simple_types<uint256_t>>>
1>        ]
1>c:\users\zxc_work\documents\visual studio 2017\projects\consoleapplication1\consoleapplication1.cpp(13): note: while trying to match the argument list '(std::_Vector_iterator<std::_Vector_val<std::_Simple_types<_Ty>>>, std::_Vector_iterator<std::_Vector_val<std::_Simple_types<_Ty>>>)'
1>        with
1>        [
1>            _Ty=uint256_t
1>        ]
1>Done building project "ConsoleApplication1.vcxproj" -- FAILED.``


hello,this is the full error message

**Comment by calccrypto** [comment]
Is the code above the actual code? Line 13 is `return 0;`

**Comment by calccrypto** [comment]
It looks like you are trying to use a `std::vector<uint256_t>::const_iterator` with a `uint256_t`. Are you dereferencing your variables?

**Comment by zxckiller** [comment]
I change to the `std::vector<uint256_t>::const_iterator`,and the error missing，very thanks!
But，in other code,  if I must use the iterator to update the element, how can i do...

**Comment by calccrypto** [comment]
Is it not the same problem? Whether or not the iterator is `const` should not be relevant. It seems that the iterator was not dereferenced.

**Comment by zxckiller** [comment]
The problem is the operator overload, when use iterator's  "==" operator ,both overload function in STL and  uint256_t can match the T ,but const_iterator seems not. 
STL:
```

	_NODISCARD bool operator==(const _Vector_const_iterator& _Right) const
		{	// test for iterator equality
		_Compat(_Right);
		return (_Ptr == _Right._Ptr);
		}
```
uint256_t:

```
bool operator==(const uint128_t & lhs, const uint256_t & rhs);

template <typename T> bool operator==(const T & lhs, const uint256_t & rhs){
    return (!rhs.upper() && ((uint64_t) lhs == rhs.lower()));
}
```

**Comment by calccrypto** [comment]
Pull the repo. I updated the templates to only match with integral types.
