### ISSUE TITLE
max/min values

### ISSUE THREAD

**Issue by skaller** [calccrypto/uint256_t#11]
At present namespace std is invaded to specify uint256_t is an integer.
However the limits traits aren't defined.

**Comment by calccrypto** [comment]
I added numeric_limits specialization for uint128_t/uint256_t, but there are some C++11/14 differences that would turn the code very ugly to make both C++11 and 14 work, so I decided to remove it for now.

**Comment by skaller** [comment]
Can you explain the differences or point at them? I couldn't see any in cppreference. [Just curious] Traits aren't a wonderful idea (especially invading namespace std to define specialisations). Heh. I'm responsible for them being called traits (not baggage which was the original proposal). Also supported the requirement that specialisations be defined in the same namespace as the entity being specialised.

**Comment by calccrypto** [comment]
numeric_limits now uses `constexpr` member functions ([```static constexpr T min(); ```](https://en.cppreference.com/w/cpp/types/numeric_limits/min)). 

Which requires something like:

```c++
constexpr uint256_t min() {
    return uint256_t(0)
}
```
Meaning that I needed `constexpr` constructors, which [have to be declared in the header file](https://stackoverflow.com/a/27345851/341683), 

Unfortunately, [`constexpr` changed between C++11 and 14](https://en.cppreference.com/w/cpp/language/constexpr) with
```
the constructor body must be either deleted or defaulted or contain only the following:

- null statements
- static_assert declarations
- typedef declarations and alias declarations that do not define classes or enumerations
- using declarations
- using directives

(until C++14)
```
to
```
the compound statement of the constructor body must satisfy the constraints for the body of a constexpr function

(since C++14)
```

Unfortunately, I have

```c++
uint256_t::uint256_t(uint256_t && rhs)
    : UPPER(std::move(rhs.UPPER)), LOWER(std::move(rhs.LOWER))
{
    if (this != &rhs){
        rhs.UPPER = uint128_0;
        rhs.LOWER = uint128_0;
    }
}
```

which violates the old rule.

I would simply not zero out the `rhs` values, but that feels like a bad idea.

**Comment by skaller** [comment]
I have some constructions in my system that use min/max for standard types.  Its not a big deal if uint256_t doesn't support this. Actually the construction is for slices over integers which look like:
```
10..20 // inclusive
21..<30 // exclusive
30.. // from  30 up
```
In principle "from 30 up" means "to infinity" but in practice I don't code that, but use the max value for the type instead.

if you think uint256_t has an issue here .. wait until you think about your "integer" library :)

I can cheat, and just use some large number. No one is every going to to loop though a slice to the maximum value representable except perhaps for char. Also I don't require the values to be constexprs, since the bounds are either constructed dynamically, or, for the constant case, the slice is always clipped (intersected) with another slice, eg a slice of a string or array is clipped by the index range 0..len-1.

So I think its OK to leave out max/min or put a dummy value or something. Not nice, but then the committee didn't think hard enough about use extensions. They'd need the function to be "optionally constexpr" which probably means another function which is constexpr to decide if it is constexpr or not ... :-) :-)

**Comment by calccrypto** [comment]
ooh boy... I suppose I can add a `uint256_max` value similar to what I did [here](https://github.com/calccrypto/uint256_t/blob/master/uint256_t.h#L376)

**Comment by calccrypto** [comment]
cafb828aa5061b7009e5eab1b86c298a808e23b5
