### ISSUE TITLE
Specify Standard version please

### ISSUE THREAD

**Issue by skaller** [calccrypto/uint256_t#13]
The code doesn't build with --std=gnu++11, which my standard setting.
I cannot change that setting for one file or one library, the whole system must use the same setting.
```
build/release/share/src/uint256_t/uint128_t.h:63:47: fatal error: no template named 'enable_if_t' in namespace 'std'; did you mean 'enable_if'?
        template <typename T, typename = std::enable_if_t <std::is_integral<T>::value> >
                                         ~~~~~^~~~~~~~~~~
                                              enable_if
```

enable_if_t requires C++14. if I move to that, my CI builds will fail. My system doesn't use build scripts which allow different configurations and options, in fact it autobuilds without any scripts, makefiles or other junk.

Please add a note in the README that C++14 is required. Thanks.

**Comment by calccrypto** [comment]
How's [this](https://github.com/calccrypto/uint256_t/commit/035ccadde81d499eb68fec78ade7bcf78c5d7e67)?

**Comment by skaller** [comment]
It doesn't build with C++11.  enable_if is C++11. enable_if_t is C++14.

**Comment by calccrypto** [comment]
Right. Thats what

```c++
#if __cplusplus >= 201402L   // C++ 14
#define ENABLE_IF_Z(T) std::enable_if_t <std::is_integral<T>::value>
#elif __cplusplus >= 201103L // C++11
#define ENABLE_IF_Z(T) typename std::enable_if <std::is_integral<T>::value, T>::type
#else
#error uint128_t requires at least C++11 to compile
#endif
```

is for.

**Comment by skaller** [comment]
Oh, sorry, didn't see that!

**Comment by skaller** [comment]
I do have a question: why use a macro? If the C++11 version works, why not just use that?
It's cleaner than a macro, which as far as I can see is pointless unless the C++11 code is deprecated or may be deprecated.

**Comment by calccrypto** [comment]
lol good point. Changed in 555114bccdd22c2e4b76635c71771558d104bfe1
