### ISSUE TITLE
dllexport stuff

### ISSUE THREAD

**Issue by skaller** [calccrypto/uint256_t#14]
I have built the code and it works fine with static linkage but there's a problem
with dynamic linkage: with clang/gcc the modern standard is -fvisibility=hidden,
and then decorate symbols to be exported with a macro that sets the visibility
to default. On Windows dll_export must be used when compiling the library,
and dll_import when using it. My system builds both static and dynamic
libraries on Linux, Osx and Windows, so exported symbol must be decorated.

Its a real pain. I hacked as solution for clang/gcc on OSX/LInux since in this
library one probably wants to export everything anyhow. But there is no
alternative for Windows, and its the right way on Unix platforms to do it as well.

Its a pity the C++ standard doesn't address dynamic linkage.

**Comment by calccrypto** [comment]
Feel free to make a pull request with the changes.

**Comment by skaller** [comment]
FYI: in principle the "three header" solution (which is not what I am using for my stuff) is probably correct. The reason is that a library exports some definitions in a header, but when building the library additional or even different definitions my be required. Some things may be left out of the public interface that the library needs internally, and some things might be changed. For example a pointer to a type T in the library may need T to be defined, but the user is not supposed to see the definition and should get a pointer to an incomplete type instead (so they can't instantiate the T value except through the API). This case is for enforcing invariants.

I would say this model is essential for large library systems, however unit256_t is a very small library with no dependencies.

**Comment by skaller** [comment]
FYI I'm looking at the C++ modules TS to see if, when available, it provides the right structure for a solution to this problem. In particular it provides 

```export decl ... ```

to export a symbol from a module. It splits module implementations from interfaces which is what is required for shared libs. We will still need macro hackery for C++11 but it would seem using a related structure to Modules TS would be good.

**Comment by skaller** [comment]
Please have a look at the fork:

https://github.com/felix-lang/uint256_t

I have NO IDEA how to test it :-)

**Comment by skaller** [comment]
OK, I submitted a PR. I have checked only that it compiles with clang, gcc, and MSVC, and one test case works. I have not run the google/unit test stuff because I have no idea how.

**Comment by skaller** [comment]
Finally it passes all tests. The README needs to be fixed.

Sorry what  happened is that I tested on C++14 but your tests use C++11. Because I renamed files when I'd finished and merged your changes in it seems they were lost because git couldn't track them.

**Comment by calccrypto** [comment]
I merged #15 and incorporated the changes into uin128_t
