### ISSUE TITLE
Calling function export_bits causes SigSegv

### ISSUE THREAD

**Issue by jiri-otoupal** [calccrypto/uint256_t#20]
If i create any number uint128 or uint256 
and try to export_bits()
it throws Segmentation fault
![Screenshot from 2020-09-03 02-55-23](https://user-images.githubusercontent.com/69390758/92059218-fa61ac00-ed90-11ea-80c5-412cb67c3a92.png)

**Comment by calccrypto** [comment]
Can you please elaborate a little/provide a minimal example code? I do not see how this could possibly segfault, since `uint128_t` uses automatic `uint64_t`s, and this function uses `std::vector<uint8_t>`, whose memory is managed.
