### ISSUE TITLE
cannot find -lgtest

### ISSUE THREAD

**Issue by GarrettEHill** [calccrypto/uint256_t#4]
Everything seems to build fine up to the following:
`
g++ -std=c++11 -Wall -g -I../../googletest/googletest/include -I.. test.cpp ../uint256_t.o ../uint128_t.o testcases/constructor.o testcases/assignment.o testcases/typecast.o testcases/accessors.o testcases/and.o testcases/or.o testcases/xor.o testcases/invert.o testcases/leftshift.o testcases/rightshift.o testcases/logical.o testcases/gt.o testcases/gte.o testcases/lt.o testcases/lte.o testcases/equals.o testcases/notequals.o testcases/add.o testcases/sub.o testcases/mult.o testcases/div.o testcases/mod.o testcases/fix.o testcases/unary.o testcases/functions.o -L../../googletest/googlemock/gtest -lgtest -lpthread -o test
`

which results with the following output:

/bin/ld: cannot find -lgtest
collect2: error: ld returned 1 exit status
Makefile:47: recipe for target 'test' failed
make: *** [test] Error 1

**Comment by calccrypto** [comment]
gtest should be placed in the same directory as uint256_t:

    /github/googletest
    /github/uint256_t

It really should be included with the repo, but it is massive.
