### ISSUE TITLE
Port request

### ISSUE THREAD

**Issue by SandeepanSengupta** [calccrypto/uint256_t#5]
This project is beautiful.
Is it possible to port it to @arduino.
It will be great for beginners like us to have such feature in @arduino.
Currently it(@arduino) only supports uint64_t

**Comment by calccrypto** [comment]
Is there some reason why you cannot just copy both `uin128_t` and `uint256_t` into your arduino code? `uint256_t` is just a wrapper around `uint64_t` via `uint128_t`.

**Comment by SandeepanSengupta** [comment]
Thank you for replying @calccrypto.
I can do that, but for ease of usage, a .json file will be great as most user prefers to use library manager feature on @arduino.
Regards,
@SandeepanSengupta

**Comment by calccrypto** [comment]
Can you provide a link/example for what you would like added? I have not kept up with arduino news in years.

**Comment by SandeepanSengupta** [comment]
My bad, I got confused between library manager and boards manager.
What I'm asking for is porting this library to @arduino in [this](https://www.arduino.cc/en/Guide/Libraries#toc2)
BTW, the library is not working by simple zip import method

**Comment by calccrypto** [comment]
Oh. What's wrong with the zip import method? What error are you getting?

**Comment by SandeepanSengupta** [comment]
Sorry for not being able to point the issue properly.

Here is the error message

__
uint128_t.cpp:262: error: exception handling disabled, use -fexceptions to
enable
         throw std::domain_error("Error: division or modulus by 0");

                                                                  ^

exception handling disabled, use -fexceptions to enable__

**Comment by SandeepanSengupta** [comment]
Here is the source

**Comment by calccrypto** [comment]
Arduinos (not surprisingly) do not support exceptions very well. If you know where your build configuration files are, I suggest that you add `-fexceptions` to the compiler options. If not, I guess, just replace the `throw` lines with bad return values.

Also, did you attach files with your last comment/email? If so, they are not accessible through Github.
