### ISSUE TITLE
How to test?

### ISSUE THREAD

**Issue by daichunkai** [calccrypto/uint256_t#7]
Hello,When I want to  test,I can't compile ,because it shows I have no a file whose name is `gtest/gtest.h`,so What should I download this file?

**Comment by calccrypto** [comment]
`gtest.h` comes from [Google Test](https://github.com/google/googletest). It is set up in Travis CI to be downloaded to the same directory as `uint256_t`.  Please see the `before_script` section of [`.travis.yml`](https://github.com/calccrypto/uint256_t/blob/master/.travis.yml#L25).
